# action.yml
name: 'Mirror Images'
description: 'Mirror images from dockerhub to other registries(ghcr,quay)'
inputs:
  config-file-path:  # id of input
    description: 'File contains the config of docker images'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.config-file-path }}
