destination_registries: 
  - ghcr.io
  - quay.io
repo_prefix: "glueops/mirror"
time_span: 5m # d,m default to 3d
images:
  - image: docker.io/grafana/grafana
    tags:
      - "10.4.13"
      # - "10.4.*"
  - image: docker.io/grafana/loki
    tags: 
      - "2.9.10"
  - image: docker.io/syepes/network_exporter
    tags: 
      - "1.7.9"
  - image: docker.io/grafana/promtail
    tags: 
      - "2.9.10"
  - image: docker.io/hashicorp/vault
    tags: 
      - "1.14.10"
  - image: docker.io/kubesphere/fluent-operator
    tags: 
      - "v2.7.0"