name: Test Docker on GitHub Actions

on:
  pull_request:
  push:
    branches: 
      - master

jobs:
  push_container:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Action
        id: mirror
        uses: ./
        with:
          config_file_path: values.yaml
        env:
          SECRET_BASE64: ${{ secrets.SECRET_BASE64 }}